var xmlns="http://www.w3.org/2000/svg",xlinkns="http://www.w3.org/1999/xlink",select=function (s){return document.querySelector(s);},selectAll=function(s){return document.querySelectorAll(ds);},mainSVG=select(".mainSVG"),box=select(".box"),connector=select("#connector"),connectorGroup=select("#connectorGroup"),dragger=select("#dragger"),graphDot=select("#graphDot"),boxLabel=select("#boxLabel"),nullDot=select("#nullDot"),graphLine=select("#graphLine"),graphBezier=MorphSVGPlugin.pathDataToBezier(graphLine.getAttribute("d")),perc,boxPos={x:0,y:0,},isPressed=false;TweenMax.set("svg",{visibility:"visible",});
TweenMax.set([dragger,graphDot,nullDot],{transformOrigin:"50% 50%",});
TweenMax.set([box],{transformOrigin:"50% 100%",});
var tl=new TimelineMax({onUpdate:updateGraph,paused:true,});
tl.to([graphDot,dragger],5,{bezier:{type:"cubic",values:graphBezier,autoRotate:false,},ease:Linear.easeNone,});
function updateTimeline(){perc=nullDot._gsTransform.x/770,TweenMax.to(tl,0.5,{progress:perc,});}
function updateGraph(){boxPos.x=dragger._gsTransform.x-box.getBBox().width/2;boxPos.y=dragger._gsTransform.y-box.getBBox().height*3;TweenMax.to(box,1,{x:boxPos.x,y:boxPos.y,ease:Elastic.easeOut.config(0.7,0.7),});boxLabel.textContent=parseInt(600-dragger._gsTransform.y)-118;}
function graphPress() {isPressed=true;TweenMax.to(dragger,1,{attr:{r:30,},ease:Elastic.easeOut.config(1, 0.7),});TweenMax.to(connector, 0.6,{attr:{x1:dragger._gsTransform.x,x2:dragger._gsTransform.x,y1:boxPos.y,y2:dragger._gsTransform.y,},});TweenMax.to(connector,0.1,{attr:{x1:box._gsTransform.x+40,x2:boxPos.x+40,y1:box._gsTransform.y+20,y2:graphDot._gsTransform.y,},onComplete:function(){TweenMax.to(box,0.8,{scale:1,alpha:1,y:boxPos.y,ease:Elastic.easeOut.config(1.2,0.7),});},});}
function graphRelease(){isPressed=false;TweenMax.to(dragger,0.3,{attr:{r:15,},ease:Elastic.easeOut.config(0.7,0.7),});TweenMax.to(box, 0.2,{scale:0,alpha:0,y:boxPos.y+30,ease:Anticipate.easeOut,});}
updateTimeline();tl.progress(0.000001);var introTl=new TimelineMax({onComplete:init,delay:1,});
introTl.staggerFrom("#horizontalLinesGroup line",1,{drawSVG:"100% 100%",alpha:1,transformOrigin:"0% 100%",},0.1)
.staggerFrom("#graphTextGroup text",1,{alpha:0,},0.1,"-=0.5")
.from([graphDot, dragger],0.71,{attr:{r:0,},ease: Power1.easeOut,},"-=1.3")
.from(graphLine,2.3,{drawSVG:"0% 0%",ease:Power3.easeInOut,},"-=1.73");
function connectLine(){if (isPressed) {TweenMax.set(connector, {attr:{x1:box._gsTransform.x+40,x2:boxPos.x+40,y1:box._gsTransform.y+43,y2:graphDot._gsTransform.y,},});} else {TweenMax.to(connector,0.1,{attr:{x1:graphDot._gsTransform.x,x2:graphDot._gsTransform.x,y1:graphDot._gsTransform.y,y2:graphDot._gsTransform.y,},});}}
function init(){Draggable.create(nullDot,{type:"x",trigger:dragger,onPress:graphPress,bounds:{minX:0,maxX:770,},zIndexBoost:false,onDrag:updateTimeline,onRelease:graphRelease,onThrowUpdate:updateTimeline,});TweenMax.ticker.addEventListener("tick",connectLine);graphRelease();}
var galleryThumbs = new Swiper(".gallery-thumbs",{effect: "coverflow",grabCursor:true,centeredSlides:true,slidesPerView:"2",coverflowEffect:{rotate:0,stretch:0,depth:50,modifier:6,slideShadows:false,},});
var galleryTop = new Swiper(".swiper-container.testimonial",{speed:400,spaceBetween:50,autoplay:{delay:3000,disableOnInteraction:false,},direction:"vertical",pagination:{clickable:true,el:".swiper-pagination",type:"bullets",},thumbs:{swiper:galleryThumbs,},});
jQuery(document).ready(function(){jQuery(".panel-slider").slick({arrows:false,speed:1000,infinite:true,autoplay:false,autoplaySpeed:3000,});});
$(document).ready(function (){$("#parentHorizontalTab").easyResponsiveTabs({type:"default",width:"auto",fit:true,tabidentify:"hor_1",activate:function(event){var $tab = $(this);var $info=$("#nested-tabInfo");var $name=$("span", $info);$name.text($tab.text());$info.show();},});$("#ChildVerticalTab_1").easyResponsiveTabs({type:"vertical",width:"auto",fit:true,tabidentify:"ver_1",activetab_bg:"#fff",inactive_bg:"#F5F5F5",active_border_color:"#c1c1c1",active_content_border_color:"#5AB1D0",});$("#parentVerticalTab").easyResponsiveTabs({type:"vertical",width:"auto",fit:true,closed:"accordion",tabidentify:"hor_1",activate:function(event){var $tab=$(this);var $info=$("#nested-tabInfo2");var $name=$("span", $info);$name.text($tab.text());$info.show();},});});